// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个任务请求
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务唯一ID
	Param         string                 `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`                 // 任务参数
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`            // 超时时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_api_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *TaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 单个任务响应
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                     // 处理结果
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` // 错误信息（失败时）
	NodeAddr      string                 `protobuf:"bytes,5,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"` // 处理节点地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_api_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *TaskResponse) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

// 批量任务请求
type BatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []string               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`                               // 多个任务参数
	ParallelNum   int32                  `protobuf:"varint,2,opt,name=parallel_num,json=parallelNum,proto3" json:"parallel_num,omitempty"` // 并行处理节点数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTaskRequest) Reset() {
	*x = BatchTaskRequest{}
	mi := &file_api_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTaskRequest) ProtoMessage() {}

func (x *BatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTaskRequest.ProtoReflect.Descriptor instead.
func (*BatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{2}
}

func (x *BatchTaskRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BatchTaskRequest) GetParallelNum() int32 {
	if x != nil {
		return x.ParallelNum
	}
	return 0
}

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api/service.proto\x12\aservice\"V\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05param\x18\x02 \x01(\tR\x05param\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"\x93\x01\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tnode_addr\x18\x05 \x01(\tR\bnodeAddr\"M\n" +
	"\x10BatchTaskRequest\x12\x16\n" +
	"\x06params\x18\x01 \x03(\tR\x06params\x12!\n" +
	"\fparallel_num\x18\x02 \x01(\x05R\vparallelNum2\x91\x01\n" +
	"\vTaskService\x12:\n" +
	"\vProcessTask\x12\x14.service.TaskRequest\x1a\x15.service.TaskResponse\x12F\n" +
	"\x10BatchProcessTask\x12\x19.service.BatchTaskRequest\x1a\x15.service.TaskResponse0\x01B\x0eZ\f../pkg/protob\x06proto3"

var (
	file_api_service_proto_rawDescOnce sync.Once
	file_api_service_proto_rawDescData []byte
)

func file_api_service_proto_rawDescGZIP() []byte {
	file_api_service_proto_rawDescOnce.Do(func() {
		file_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)))
	})
	return file_api_service_proto_rawDescData
}

var file_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_service_proto_goTypes = []any{
	(*TaskRequest)(nil),      // 0: service.TaskRequest
	(*TaskResponse)(nil),     // 1: service.TaskResponse
	(*BatchTaskRequest)(nil), // 2: service.BatchTaskRequest
}
var file_api_service_proto_depIdxs = []int32{
	0, // 0: service.TaskService.ProcessTask:input_type -> service.TaskRequest
	2, // 1: service.TaskService.BatchProcessTask:input_type -> service.BatchTaskRequest
	1, // 2: service.TaskService.ProcessTask:output_type -> service.TaskResponse
	1, // 3: service.TaskService.BatchProcessTask:output_type -> service.TaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
		MessageInfos:      file_api_service_proto_msgTypes,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
